### ISSUE TITLE
Change cipher strength

### ISSUE THREAD

**Issue by syedaali** [kylemanna/docker-openvpn#184] opened 2016-12-05 07:23 UTC
When I view OpenVPN client log upon connection, I see the following warning:

WARNING: this cipher's block size is less than 128 bit (64 bit). Consider using a --cipher with a larger block size.

This request is to make the default block size 128 bit.

**Comment by kylemanna** [comment] 2016-12-05 07:37
Duplicate of #163

**Closed by kylemanna** 2016-12-05 07:37 UTC
