### ISSUE TITLE
WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).

### ISSUE THREAD

**Issue by ops0824** [kylemanna/docker-openvpn#349] opened 2017-12-27 08:28 UTC
WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
...
WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.

**Comment by kylemanna** [comment] 2017-12-27 12:31
Duplicate of #163 #290 and #291 

Please update your client.

**Closed by kylemanna** 2017-12-27 12:31 UTC
