### ISSUE TITLE
Reach outside of Docker container to interact with host services

### ISSUE THREAD

**Issue by looterz** [kylemanna/docker-openvpn#110] opened 2016-03-03 16:54 UTC
Is this possible using this image yet? It would be useful when using this image as the openvpn server, but also accessing services available only on the local network of the machine that is hosting the container, as with traditional VPN setups. For instance, accessing a mongod instance that only accepts local connections.

**Comment by GetafixIT** [comment] 2016-03-23 12:06
I'm also trying to do the same. I've tried to setup using the various config options, currently:

docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn ovpn_genconfig -u udp://vpn.mydomain.com -c -N

I'm in hosted in AWS and need to restrict the inbound traffic so services in my docker cloud are only available when connected through the VPN. Can't quite figure out this last piece... @looterz did you find a solution? Or any pointers @kylemanna?

**Comment by looterz** [comment] 2016-03-23 12:39
I never did find a solution to this issue, unfortunately.

**Comment by GetafixIT** [comment] 2016-03-24 10:50
Think it's an issue with the ip routing of the docker container... and/or the ovpn config. I'm not sure about this as it's outside my normal skill set. Think that I need to add some params to the ovpn config: 

- add -t to allow tap connectivity (the docker container should already have a bridged network interface). Read somewhere that you need this mode to share the hosts resources.
- add a route with -r 10.1.0.1 0.0.0.0 ... or something like that shown from the host or docker container 'route' command

It might also be that I need to add a loopback adapter... or perhaps something to the hosts file on the host / ovpn container (the host machine can't reach it's own public ip and might need mapping to it's private ip). 

Will let you know if I figure it out.

**Comment by GetafixIT** [comment] 2016-03-24 14:25
I've got it working for my situation... basically I have a cloud of docker containers - in essence a series of web apps. They are behind an nginx proxy (also in docker). I'm hosted in AWS and have now closed port 80 on the inbound traffic since I have the VPN working now and all traffic reaches my instance through the tunnel.

This means that none of my dockerised web apps are publicly available... unless you're connected to the VPN.

To do this I've added some additional config to whats described for this docker image:

-r [AWS private IP] -c -t

I am actually not 100% that this additional route is required... need to re-test without it. The missing piece was to add to the hosts file on the local machine / vpn client machine. I added the:

[AWS private IP] subdomain.yourdomain.com othersubdomain.yourdomain.com

Now it's working for my use-case. Hope this helps :)

**Comment by ragaar** [comment] 2016-03-28 00:11
This looks to be a duplicate of #109.

**Comment by devotox** [comment] 2016-03-30 08:03
So does this mean that you would need 2 instances of an AWS machine and you couldn't use something like docker-compose and run all containers on the same instance and just allow only a connection to the VPN and then while in the private network connected to the vpn be able to connect to the the other containers just by container name?

**Comment by jedwards1211** [comment] 2016-07-15 01:07
@GetafixIT thanks so much for sharing what worked for you!  I had to do something a little different (-t didn't work for me):

`-r [AWS Private IP] -n [AWS DNS Server] -c`

The DNS server was necessary to access other AWS instances than the one my OpenVPN was running on.

**Comment by jedwards1211** [comment] 2016-07-15 01:09
@devotox I *think* you wouldn't need to do anything beyond the instructions in the README to access other containers on the same host as the OpenVPN container, as long as you connect to public ports on those containers.

**Comment by bartoszhernas** [comment] 2016-08-18 11:19
Hey, so here is my solution to hide docker containers behind this VPN:

1) I run OpenVPN with `"network_mode": "host"` (in docker-compse, for normal docker run you just say `--net host`)
2) Then I run other container with port mapping like this: 

```
    ports:
      - "192.168.255.1:80:80"
```

In my case I run jenkins with internal port, and nginx-proxy separatelly that is exposed the way I described, and it proxy passes the traffic to jenkins:


When I will be running more tools there I will probably just set up `nginx-proxy`

**Comment by kylemanna** [comment] 2017-01-01 23:35
Closing due to no updates in a few months.

**Closed by kylemanna** 2017-01-01 23:35 UTC

**Comment by konstantinj** [comment] 2017-09-25 13:55
Hi @kylemanna and @bartoszhernas 
I'm still trying to achieve this without luck.

Have tried spawning the openvpn container in host mode and another container binding to 192.168.255.1.  The other container then can ping my connected client e.g. 192.168.255.6. But the other container does not have an address in 192.168.255.0 so I cannot ping it from the client.

**Comment by cklinx** [comment] 2019-04-14 22:41
thanks so muck @bartoszhernas!
