### ISSUE TITLE
cipher warnings in server logs

### ISSUE THREAD

**Issue by ensonic** [kylemanna/docker-openvpn#205] opened 2017-01-17 13:26 UTC
I see a few warnings in the log of the vpn server when a client connects:

```
Data Channel Encrypt: Cipher 'BF-CBC' initialized with 128 bit key
WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Data Channel Decrypt: Cipher 'BF-CBC' initialized with 128 bit key
WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.
Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
```

from reading docs/paranoid.md, those should be fixable using ```-C 'AES-256-CBC'  -a 'SHA384'```. Any reason those are not defaults?

**Comment by kylemanna** [comment] 2017-01-17 15:09
Duplicate of #163

**Closed by kylemanna** 2017-01-17 15:09 UTC

**Comment by kylemanna** [comment] 2017-01-17 15:23
This is most likely caused by your OpenVPN client.  Upgrade it and it'll negotiate a strong cipher.
