### ISSUE TITLE
Still able to authenticate with revoked keys

### ISSUE THREAD

**Issue by ishan-marikar** [kylemanna/docker-openvpn#183] opened 2016-11-29 17:46 UTC
I installed this recently and have been enjoying and learning a lot from it, but I've noticed that (I think) that the documentation was a bit outdated. I still managed to figure out how to get basic stuff working and wrote functions to make my work easier.

``` sh 
function vpn-create-client {
	if [[ $# -eq 0 ]] ; then
		echo "Argument missing: vpn-create-client <client-name>"
	else
		echo "Creating account for $1"
		docker run --volumes-from $OVPN_DATA --rm -it kylemanna/openvpn easyrsa build-client-full $1 nopass
		docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn ovpn_getclient $1 > $1.ovpn
	fi
}

function vpn-ls-client {
	docker run --rm -i --volumes-from $OVPN_DATA kylemanna/openvpn ovpn_listclients
}

function vpn-revoke-client {
        if [[ $# -eq 0 ]] ; then
                echo 'Argument missing: vpn-revoke-client <client-name>'
        else
               # docker run --rm -it -v $OVPN_DATA:/etc/openvpn kylemanna/openvpn easyrsa revoke $1
	       # docker run --rm -it -v $OVPN_DATA:/etc/openvpn kylemanna/openvpn easyrsa gen-crl

		docker run --rm -i --volumes-from $OVPN_DATA -e "EASYRSA_BATCH=1" kylemanna/openvpn easyrsa revoke $1
		docker run --rm -i --volumes-from $OVPN_DATA kylemanna/openvpn easyrsa gen-crl
        fi

}
```

I did come across a certain problem though. I noticed that I could still authenticate and connect with revoked certificates.

```
name,begin,end,status
home-laptop,Nov 26 18:59:27 2016 GMT,Nov 24 18:59:27 2026 GMT,VALID
test,Nov 26 19:54:38 2016 GMT,Nov 24 19:54:38 2026 GMT,REVOKED
```

Even though test is 'REVOKED', I could still use tunnelblick to connect to it.
<img width="282" alt="screen shot 2016-11-29 at 11 12 46 pm" src="https://cloud.githubusercontent.com/assets/7364188/20721593/666797fe-b689-11e6-8b5f-3685a75df536.png">

.. and when re-running the revoke commands, I get this:
```
--- SNIPPED ---

ERROR:Already revoked, serial number 03

--- SNIPPED ---
```

**Comment by kylemanna** [comment] 2016-11-29 19:49
Duplicate of #101

**Closed by kylemanna** 2016-11-29 19:49 UTC
